// if (process.env.NODE_ENV !== 'development') {
//   require('module-alias/register');
//   console.log('module-alias/register');
// }
import appRootPath from 'app-root-path';
import { generateController } from 'codegen/generateController';
import { generateCommonTypes } from 'codegen/generateCommonTypes';
import { deleteRouterSync } from 'codegen/routerStorage';
import { sleep } from 'scub111-common';
import { GlobalVar, dbConnectionSingleton } from '@mapbul-pub/common';

export const generateControllers = async () => {
  console.log('test5');
  // await sleep(1000);
  const t0 = new Date();
  GlobalVar.setup(`${appRootPath}/.env`);
  const dbConnection = dbConnectionSingleton.getInstance();
  deleteRouterSync();
  await generateController(dbConnection, 'admin', 'admin', 'admins');
  await generateController(dbConnection, 'article', 'article', 'articles');
  await generateController(dbConnection, 'articlesubcategory', 'articleSubcategory', 'articleSubcategories');
  await generateController(dbConnection, 'category', 'category', 'categories');
  await generateController(dbConnection, 'city', 'city', 'cities');
  await generateController(dbConnection, 'city_permission', 'cityPermission', 'cityPermissions');
  await generateController(dbConnection, 'country', 'country', 'countries');
  await generateController(dbConnection, 'country_permission', 'countryPermission', 'countryPermissions');
  await generateController(dbConnection, 'discount', 'discount', 'discounts');
  await generateController(dbConnection, 'editor', 'editor', 'editors');
  await generateController(dbConnection, 'favorites_article', 'favoritesArticle', 'favoritesArticles');
  await generateController(dbConnection, 'favorites_marker', 'favoritesMarker', 'favoritesMarkers');
  await generateController(dbConnection, 'guide', 'guide', 'guides');
  await generateController(dbConnection, 'journalist', 'journalist', 'journalists');
  await generateController(dbConnection, 'marker', 'marker', 'markers');
  await generateController(dbConnection, 'marker_photos', 'markerPhotos', 'markerPhotos');
  await generateController(dbConnection, 'marker_request_session', 'markerRequestSession', 'markerRequestSessions');
  await generateController(dbConnection, 'phone', 'phone', 'phones');
  await generateController(dbConnection, 'region', 'region', 'regions');
  await generateController(dbConnection, 'region_permission', 'regionPermission', 'regionPermissions');
  await generateController(dbConnection, 'status', 'status', 'statuses');
  await generateController(dbConnection, 'subcategory', 'subcategory', 'subcategories');
  await generateController(dbConnection, 'tenant', 'tenant', 'tenants');
  await generateController(dbConnection, 'user', 'user', 'users');
  await generateController(dbConnection, 'usertype', 'userType', 'userTypes');
  await generateController(dbConnection, 'weekday', 'weekDay', 'weekDays');
  await generateController(dbConnection, 'worktime', 'workTime', 'workTimes');
  dbConnection.disconnect();
  const diff = new Date().valueOf() - t0.valueOf();
  await generateCommonTypes();
  console.log(`${diff} ms`);
};
