export interface IMarkerDTO {
  id: number;
  name: string;
  nameEn: string | null;
  introduction: string;
  introductionEn: string | null;
  description: string;
  descriptionEn: string | null;
  cityId: number;
  baseCategoryId: number;
  lat: number;
  lng: number;
  entryTicket: string | null;
  discountId: number;
  street: string;
  house: string;
  buliding: string | null;
  floor: string | null;
  site: string | null;
  email: string | null;
  photo: string | null;
  userId: number;
  addedDate: Date;
  publishedDate: Date | null;
  checkDate: Date | null;
  statusId: number;
  logo: string | null;
  wifi: boolean;
  personal: boolean;
}
